# Use an official Node.js runtime as a parent image
FROM node:14 as build

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Install any needed packages
RUN npm install

ARG REACT_APP_API_BASE_URL

ENV REACT_APP_API_BASE_URL $REACT_APP_API_BASE_URL
# Build the app for production
RUN npm run build

# Stage 2: Serve the React application
FROM nginx:alpine

# Copy the build output to the NGINX html directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom NGINX configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
